apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loja-online
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Diogokranzz/Kubernetes.git'
    targetRevision: HEAD
    path: k8s-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
